version: '3.7'

services:
  botservice:
    build:
      context: ./botservice
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    # volumes:
    #   - ./app:/app
    ports:
      - 8000:8000
    expose: 
      - "8000"
    env_file:
      - ./.env
    # depends_on:
    #   - db
  # db:
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=hello_django
  #     - POSTGRES_PASSWORD=hello_django
  #     - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:


      # command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn --workers=3 core.wsgi -b 0.0.0.0:8000"